### ISSUE TITLE
Use more of the CDD principles on your landing page

### ISSUE THREAD

**Issue by HarrisonJackson** [smu-gui-spring-2015/KristoforHorst#10]
This article may help:
http://blog.hubspot.com/marketing/principles-of-conversion-centered-landing-page-design

**Comment by KristoforHorst** [comment]
I've increased the black box, changed the text color, and added some content to create a stronger call to action. The testimonial content and other features are below the fold now (or should be). I hope this is a sufficient solution to the issues, and if it's not maybe we can sit down to a meeting and discuss it.
